repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: ["--line-length=100"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=100"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: ["--select=E,F,I,UP,B"]
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ["--convention=google"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-setuptools"]
  - repo: https://github.com/pytest-dev/pytest
    rev: 7.4.3
    hooks:
      - id: pytest
        args: ["-q"]
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: python scripts/commitlint.py
        language: system
        stages: [commit-msg]
        pass_filenames: true
