name: Feature Request
description: Suggest an idea
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an idea!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the feature
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: How should it work?
    validations:
      required: true
