name: Auto PR Merge

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run lint and tests
        id: initial
        continue-on-error: true
        run: |
          black --check .
          isort --check-only .
          flake8 .
          mypy addons tests
          pytest -q
      - name: Apply auto fixes
        if: steps.initial.outcome == 'failure'
        run: python scripts/auto_fix.py
      - name: Push fixes
        if: steps.initial.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git push origin HEAD:${{ github.head_ref }}
            gh pr comment $PR_NUMBER -b "Auto fixes applied. Re-running checks."
          fi
      - name: Re-run lint and tests
        if: steps.initial.outcome == 'failure'
        id: retry
        continue-on-error: true
        run: |
          black --check .
          isort --check-only .
          flake8 .
          mypy addons tests
          pytest -q
      - name: Comment failure
        if: steps.initial.outcome == 'failure' && steps.retry.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment $PR_NUMBER -b "Checks failed. Manual review required."
      - name: Merge PR
        if: steps.initial.outcome == 'success' || steps.retry.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment $PR_NUMBER -b "All checks passed. Merging PR."
          gh pr merge $PR_NUMBER --merge --admin
