name: CI

on: [push, pull_request]

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
bootstrap-empty-github-repo-for-blender-project
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

bootstrap-empty-github-repo-for-blender-project
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
main

        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Black
        run: black --check .
      - name: Isort
        run: isort --check-only .
      - name: Flake8
        run: flake8 .
      - name: Mypy
        run: mypy addons tests
      - name: Pytest
        run: pytest -q
